// Sport England Place Partnership locations
// Categories: existing_ldp, transition_core, place_expansion
const SE_PLACES = [
    // From Phase 1 tables (user-provided images)
    {name:"Dudley",coverage:"MSOAs",type:"place_expansion",lat:52.511,lng:-2.082},
    {name:"Sandwell",coverage:"Whole Place",type:"place_expansion",lat:52.506,lng:-2.011},
    {name:"Walsall",coverage:"Whole Place",type:"place_expansion",lat:52.585,lng:-1.982},
    {name:"Wolverhampton",coverage:"Whole Place",type:"place_expansion",lat:52.587,lng:-2.128},
    {name:"Cheshire East",coverage:"MSOAs",type:"place_expansion",lat:53.15,lng:-2.21},
    {name:"Cheshire West and Chester",coverage:"MSOAs",type:"place_expansion",lat:53.19,lng:-2.75},
    {name:"Warrington",coverage:"MSOAs",type:"place_expansion",lat:53.39,lng:-2.60},
    {name:"Cumberland",coverage:"MSOAs",type:"place_expansion",lat:54.66,lng:-2.90},
    {name:"Castle Point",coverage:"MSOAs",type:"existing_ldp",lat:51.55,lng:0.57},
    {name:"Harlow",coverage:"Whole Place",type:"place_expansion",lat:51.78,lng:0.08},
    {name:"Thurrock",coverage:"MSOAs",type:"place_expansion",lat:51.49,lng:0.31},
    {name:"Hull",coverage:"Whole Place",type:"place_expansion",lat:53.744,lng:-0.339},
    {name:"North East Lincolnshire",coverage:"MSOAs",type:"existing_ldp",lat:53.567,lng:-0.079},
    {name:"Gravesham",coverage:"MSOAs",type:"existing_ldp",lat:51.44,lng:0.37},
    {name:"Thanet",coverage:"Whole Place",type:"existing_ldp",lat:51.36,lng:1.39},
    {name:"Blackpool",coverage:"Whole Place",type:"place_expansion",lat:53.818,lng:-3.051},
    {name:"Boston",coverage:"Whole Place",type:"existing_ldp",lat:52.978,lng:-0.024},
    {name:"East Lindsey",coverage:"Whole Place",type:"existing_ldp",lat:53.143,lng:0.341},
    {name:"Great Yarmouth",coverage:"Whole Place",type:"place_expansion",lat:52.607,lng:1.731},
    {name:"King's Lynn and West Norfolk",coverage:"MSOAs",type:"place_expansion",lat:52.75,lng:0.39},
    {name:"Ashfield",coverage:"MSOAs",type:"place_expansion",lat:53.090,lng:-1.252},
    {name:"Nottingham",coverage:"MSOAs",type:"place_expansion",lat:52.950,lng:-1.150},
    {name:"Derby",coverage:"MSOAs",type:"place_expansion",lat:52.919,lng:-1.468},
    {name:"Erewash",coverage:"MSOAs",type:"place_expansion",lat:52.93,lng:-1.32},
    {name:"Ipswich",coverage:"Whole Place",type:"place_expansion",lat:52.058,lng:1.153},
    {name:"West Suffolk",coverage:"MSOAs",type:"place_expansion",lat:52.25,lng:0.72},
    {name:"Spelthorne",coverage:"MSOAs",type:"place_expansion",lat:51.43,lng:-0.44},
    {name:"Leicester",coverage:"Whole Place",type:"place_expansion",lat:52.623,lng:-1.135},
    {name:"Portsmouth",coverage:"MSOAs",type:"place_expansion",lat:50.800,lng:-1.091},
    {name:"Southampton",coverage:"Whole Place",type:"place_expansion",lat:50.903,lng:-1.404},
    {name:"Slough",coverage:"MSOAs",type:"place_expansion",lat:51.51,lng:-0.59},
    {name:"Milton Keynes",coverage:"MSOAs",type:"place_expansion",lat:52.04,lng:-0.76},
    {name:"Fenland",coverage:"Whole Place",type:"place_expansion",lat:52.60,lng:0.10},
    {name:"Peterborough",coverage:"Whole Place",type:"place_expansion",lat:52.57,lng:-0.24},
    {name:"Barking and Dagenham",coverage:"Whole Place",type:"place_expansion",lat:51.540,lng:0.079},
    {name:"Brent",coverage:"MSOAs",type:"existing_ldp",lat:51.56,lng:-0.27},
    {name:"Tower Hamlets",coverage:"Whole Place",type:"place_expansion",lat:51.52,lng:-0.03},
    {name:"Knowsley",coverage:"Whole Place",type:"place_expansion",lat:53.482,lng:-2.889},
    {name:"Liverpool",coverage:"Whole Place",type:"place_expansion",lat:53.408,lng:-2.992},
    {name:"Sefton",coverage:"MSOAs",type:"place_expansion",lat:53.50,lng:-3.00},
    {name:"Wirral",coverage:"MSOAs",type:"place_expansion",lat:53.37,lng:-3.03},
    {name:"North Northamptonshire",coverage:"MSOAs",type:"place_expansion",lat:52.40,lng:-0.69},
    {name:"West Northamptonshire",coverage:"MSOAs",type:"place_expansion",lat:52.24,lng:-0.89},
    {name:"Gateshead",coverage:"MSOAs",type:"place_expansion",lat:54.96,lng:-1.60},
    {name:"South Tyneside",coverage:"MSOAs",type:"place_expansion",lat:54.981,lng:-1.491},
    {name:"Darlington",coverage:"MSOAs",type:"place_expansion",lat:54.52,lng:-1.55},
    {name:"Hartlepool",coverage:"Whole Place",type:"place_expansion",lat:54.686,lng:-1.209},
    {name:"Stockton-on-Tees",coverage:"MSOAs",type:"place_expansion",lat:54.57,lng:-1.32},
    {name:"Stoke-on-Trent",coverage:"Whole Place",type:"place_expansion",lat:53.006,lng:-2.178},
    {name:"Swindon",coverage:"MSOAs",type:"place_expansion",lat:51.562,lng:-1.785},
    {name:"Barnsley",coverage:"Whole Place",type:"place_expansion",lat:53.553,lng:-1.483},
    {name:"Rotherham",coverage:"MSOAs",type:"place_expansion",lat:53.431,lng:-1.356},
    {name:"Kirklees",coverage:"MSOAs",type:"place_expansion",lat:53.62,lng:-1.78},
    // Additional from expansion map (Transition/Core Cities - dark blue)
    {name:"County Durham",coverage:"Whole Place",type:"transition_core",lat:54.70,lng:-1.60},
    {name:"Leeds",coverage:"Whole Place",type:"transition_core",lat:53.80,lng:-1.55},
    {name:"Sheffield",coverage:"Whole Place",type:"transition_core",lat:53.38,lng:-1.47},
    {name:"Manchester",coverage:"Whole Place",type:"transition_core",lat:53.48,lng:-2.24},
    {name:"Birmingham",coverage:"Whole Place",type:"transition_core",lat:52.483,lng:-1.889},
    {name:"Bristol",coverage:"Whole Place",type:"transition_core",lat:51.454,lng:-2.597},
    {name:"Plymouth",coverage:"Whole Place",type:"transition_core",lat:50.38,lng:-4.14},
    {name:"Exeter",coverage:"Whole Place",type:"transition_core",lat:50.712,lng:-3.530},
    {name:"Newcastle upon Tyne",coverage:"Whole Place",type:"transition_core",lat:54.98,lng:-1.61},
    // Additional from expansion map (Existing LDP - light blue)
    {name:"Bradford",coverage:"Whole Place",type:"existing_ldp",lat:53.794,lng:-1.752},
    {name:"Hackney",coverage:"MSOAs",type:"existing_ldp",lat:51.55,lng:-0.06},
    {name:"Basildon",coverage:"MSOAs",type:"existing_ldp",lat:51.57,lng:0.46},
    {name:"Tendring",coverage:"MSOAs",type:"existing_ldp",lat:51.79,lng:1.15},
    {name:"Colchester",coverage:"MSOAs",type:"existing_ldp",lat:51.89,lng:0.90},
    {name:"Blackburn with Darwen",coverage:"MSOAs",type:"existing_ldp",lat:53.75,lng:-2.48},
    {name:"Burnley",coverage:"MSOAs",type:"existing_ldp",lat:53.791,lng:-2.244},
    {name:"Hyndburn",coverage:"MSOAs",type:"existing_ldp",lat:53.754,lng:-2.366},
    {name:"Pendle",coverage:"MSOAs",type:"existing_ldp",lat:53.84,lng:-2.21},
    {name:"Rossendale",coverage:"MSOAs",type:"existing_ldp",lat:53.70,lng:-2.28},
    {name:"Oldham",coverage:"MSOAs",type:"existing_ldp",lat:53.54,lng:-2.12},
    {name:"Rochdale",coverage:"MSOAs",type:"existing_ldp",lat:53.61,lng:-2.16},
    // Additional from expansion map (Place Expansion - green)
    {name:"Redcar and Cleveland",coverage:"MSOAs",type:"place_expansion",lat:54.56,lng:-1.14},
    {name:"Middlesbrough",coverage:"MSOAs",type:"place_expansion",lat:54.576,lng:-1.234},
    {name:"East Riding of Yorkshire",coverage:"MSOAs",type:"place_expansion",lat:53.84,lng:-0.70},
    {name:"Wakefield",coverage:"MSOAs",type:"place_expansion",lat:53.68,lng:-1.50},
    {name:"Doncaster",coverage:"MSOAs",type:"place_expansion",lat:53.523,lng:-1.134},
    {name:"Calderdale",coverage:"MSOAs",type:"place_expansion",lat:53.72,lng:-1.86},
    {name:"Bury",coverage:"MSOAs",type:"place_expansion",lat:53.59,lng:-2.30},
    {name:"Tameside",coverage:"MSOAs",type:"place_expansion",lat:53.49,lng:-2.10},
    {name:"Salford",coverage:"MSOAs",type:"place_expansion",lat:53.48,lng:-2.29},
    {name:"Trafford",coverage:"MSOAs",type:"place_expansion",lat:53.42,lng:-2.35},
    {name:"Stockport",coverage:"MSOAs",type:"place_expansion",lat:53.41,lng:-2.16},
    {name:"Wigan",coverage:"MSOAs",type:"place_expansion",lat:53.54,lng:-2.63},
    {name:"Ribble Valley",coverage:"MSOAs",type:"place_expansion",lat:53.87,lng:-2.42},
    {name:"Coventry",coverage:"MSOAs",type:"place_expansion",lat:52.407,lng:-1.510},
    {name:"Solihull",coverage:"MSOAs",type:"place_expansion",lat:52.41,lng:-1.78},
    {name:"Gloucester",coverage:"MSOAs",type:"place_expansion",lat:51.86,lng:-2.24},
    {name:"Luton",coverage:"MSOAs",type:"place_expansion",lat:51.878,lng:-0.415},
    {name:"Ealing",coverage:"MSOAs",type:"place_expansion",lat:51.51,lng:-0.31}
];

// Nature Towns and Cities locations
// Categories: accredited_city, accredited_town, grant_recipient
const NTC_PLACES = [
    // Accredited Nature Cities
    {name:"Plymouth",type:"accredited_city",lat:50.38,lng:-4.14,project:"Plan for Nature and People"},
    {name:"Birmingham",type:"accredited_city",lat:52.483,lng:-1.889,project:"City of Nature Plan"},
    // Accredited Nature Towns
    {name:"Bournemouth",type:"accredited_town",lat:50.72,lng:-1.88,project:"BCP Nature Towns"},
    // Grant Recipients (19 partnerships, ~40 towns/cities)
    {name:"Bradford",type:"grant",lat:53.794,lng:-1.752,project:"Green Blue Steppingstones"},
    {name:"Blackpool",type:"grant",lat:53.818,lng:-3.051,project:"GreenWave: Transforming Urban Nature"},
    {name:"Liverpool",type:"grant",lat:53.408,lng:-2.992,project:"Liverpool City Region Green Vision"},
    {name:"Redcar and Cleveland",type:"grant",lat:54.56,lng:-1.14,project:"Tees Urban Nature Network"},
    {name:"Manchester",type:"grant",lat:53.48,lng:-2.24,project:"Manchester & Salford Green Vision"},
    {name:"Salford",type:"grant",lat:53.48,lng:-2.29,project:"Manchester & Salford Green Vision"},
    {name:"Sunderland",type:"grant",lat:54.91,lng:-1.38,project:"Sunderland Urban Green Spaces"},
    {name:"Bristol",type:"grant",lat:51.454,lng:-2.597,project:"Nature Together"},
    {name:"Ealing",type:"grant",lat:51.51,lng:-0.31,project:"Regional Park Vision"},
    {name:"Portsmouth",type:"grant",lat:50.800,lng:-1.091,project:"Green Vision: Urban Nature Revival"},
    {name:"Lewisham",type:"grant",lat:51.44,lng:-0.01,project:"Lewisham Green Vision"},
    {name:"Luton",type:"grant",lat:51.878,lng:-0.415,project:"Nature Connection Initiative"},
    {name:"Norwich",type:"grant",lat:52.63,lng:1.30,project:"NatureCityNorwich"},
    {name:"Walsall",type:"grant",lat:52.585,lng:-1.982,project:"Green Vision: Nature & Health"},
    {name:"Coventry",type:"grant",lat:52.407,lng:-1.510,project:"Green Renaissance"},
    {name:"Torfaen",type:"grant",lat:51.654,lng:-3.021,project:"Torfaen Nature Masterplan"},
    {name:"Neath Port Talbot",type:"grant",lat:51.595,lng:-3.782,project:"Nature's Back in Town"},
    {name:"Fife",type:"grant",lat:56.07,lng:-3.46,project:"Transforming Fife's Greenspace"},
    {name:"North Lanarkshire",type:"grant",lat:55.86,lng:-3.96,project:"NL Nearer to Nature"},
    {name:"Belfast",type:"grant",lat:54.60,lng:-5.93,project:"Belfast Nature Recovery Blueprint"}
];

window.SE_PLACES = SE_PLACES;
window.NTC_PLACES = NTC_PLACES;
