// Sport England Place Partnership locations
// Categories: existing_ldp, transition_core, place_expansion
const SE_PLACES = [
    // From Phase 1 tables (user-provided images)
    {name:"Dudley",coverage:"MSOAs",type:"place_expansion",lat:52.511,lng:-2.082},
    {name:"Sandwell",coverage:"Whole Place",type:"place_expansion",lat:52.506,lng:-2.011},
    {name:"Walsall",coverage:"Whole Place",type:"place_expansion",lat:52.585,lng:-1.982},
    {name:"Wolverhampton",coverage:"Whole Place",type:"place_expansion",lat:52.587,lng:-2.128},
    {name:"Cheshire East",coverage:"MSOAs",type:"place_expansion",lat:53.15,lng:-2.21},
    {name:"Cheshire West and Chester",coverage:"MSOAs",type:"place_expansion",lat:53.19,lng:-2.75},
    {name:"Warrington",coverage:"MSOAs",type:"place_expansion",lat:53.39,lng:-2.60},
    {name:"Cumberland",coverage:"MSOAs",type:"place_expansion",lat:54.66,lng:-2.90},
    {name:"Castle Point",coverage:"MSOAs",type:"existing_ldp",lat:51.55,lng:0.57},
    {name:"Harlow",coverage:"Whole Place",type:"place_expansion",lat:51.78,lng:0.08},
    {name:"Thurrock",coverage:"MSOAs",type:"place_expansion",lat:51.49,lng:0.31},
    {name:"Hull",coverage:"Whole Place",type:"place_expansion",lat:53.744,lng:-0.339},
    {name:"North East Lincolnshire",coverage:"MSOAs",type:"existing_ldp",lat:53.52,lng:-0.10},
    {name:"Gravesham",coverage:"MSOAs",type:"existing_ldp",lat:51.44,lng:0.37},
    {name:"Thanet",coverage:"Whole Place",type:"existing_ldp",lat:51.36,lng:1.39},
    {name:"Blackpool",coverage:"Whole Place",type:"place_expansion",lat:53.818,lng:-3.051},
    {name:"Boston",coverage:"Whole Place",type:"existing_ldp",lat:52.978,lng:-0.024},
    {name:"East Lindsey",coverage:"Whole Place",type:"existing_ldp",lat:53.259,lng:0.177},
    {name:"Great Yarmouth",coverage:"Whole Place",type:"place_expansion",lat:52.607,lng:1.731},
    {name:"King's Lynn and West Norfolk",coverage:"MSOAs",type:"place_expansion",lat:52.75,lng:0.39},
    {name:"Ashfield",coverage:"MSOAs",type:"place_expansion",lat:53.090,lng:-1.252},
    {name:"Nottingham",coverage:"MSOAs",type:"place_expansion",lat:52.950,lng:-1.150},
    {name:"Derby",coverage:"MSOAs",type:"place_expansion",lat:52.919,lng:-1.468},
    {name:"Erewash",coverage:"MSOAs",type:"place_expansion",lat:52.93,lng:-1.32},
    {name:"Ipswich",coverage:"Whole Place",type:"place_expansion",lat:52.058,lng:1.153},
    {name:"West Suffolk",coverage:"MSOAs",type:"place_expansion",lat:52.25,lng:0.72},
    {name:"Spelthorne",coverage:"MSOAs",type:"place_expansion",lat:51.43,lng:-0.44},
    {name:"Leicester",coverage:"Whole Place",type:"place_expansion",lat:52.623,lng:-1.135},
    {name:"Portsmouth",coverage:"MSOAs",type:"place_expansion",lat:50.800,lng:-1.091},
    {name:"Southampton",coverage:"Whole Place",type:"place_expansion",lat:50.903,lng:-1.404},
    {name:"Slough",coverage:"MSOAs",type:"place_expansion",lat:51.51,lng:-0.59},
    {name:"Milton Keynes",coverage:"MSOAs",type:"place_expansion",lat:52.04,lng:-0.76},
    {name:"Fenland",coverage:"Whole Place",type:"place_expansion",lat:52.60,lng:0.10},
    {name:"Peterborough",coverage:"Whole Place",type:"place_expansion",lat:52.57,lng:-0.24},
    {name:"Barking and Dagenham",coverage:"Whole Place",type:"place_expansion",lat:51.540,lng:0.079},
    {name:"Brent",coverage:"MSOAs",type:"existing_ldp",lat:51.56,lng:-0.27},
    {name:"Tower Hamlets",coverage:"Whole Place",type:"place_expansion",lat:51.52,lng:-0.03},
    {name:"Knowsley",coverage:"Whole Place",type:"place_expansion",lat:53.482,lng:-2.889},
    {name:"Liverpool",coverage:"Whole Place",type:"place_expansion",lat:53.408,lng:-2.992},
    {name:"Sefton",coverage:"MSOAs",type:"place_expansion",lat:53.50,lng:-3.00},
    {name:"Wirral",coverage:"MSOAs",type:"place_expansion",lat:53.37,lng:-3.03},
    {name:"North Northamptonshire",coverage:"MSOAs",type:"place_expansion",lat:52.40,lng:-0.69},
    {name:"West Northamptonshire",coverage:"MSOAs",type:"place_expansion",lat:52.24,lng:-0.89},
    {name:"Gateshead",coverage:"MSOAs",type:"place_expansion",lat:54.96,lng:-1.60},
    {name:"South Tyneside",coverage:"MSOAs",type:"place_expansion",lat:54.958,lng:-1.410},
    {name:"Darlington",coverage:"MSOAs",type:"place_expansion",lat:54.52,lng:-1.55},
    {name:"Hartlepool",coverage:"Whole Place",type:"place_expansion",lat:54.686,lng:-1.209},
    {name:"Stockton-on-Tees",coverage:"MSOAs",type:"place_expansion",lat:54.57,lng:-1.32},
    {name:"Stoke-on-Trent",coverage:"Whole Place",type:"place_expansion",lat:53.006,lng:-2.178},
    {name:"Swindon",coverage:"MSOAs",type:"place_expansion",lat:51.562,lng:-1.785},
    {name:"Barnsley",coverage:"Whole Place",type:"place_expansion",lat:53.553,lng:-1.483},
    {name:"Rotherham",coverage:"MSOAs",type:"place_expansion",lat:53.431,lng:-1.356},
    {name:"Kirklees",coverage:"MSOAs",type:"place_expansion",lat:53.62,lng:-1.78},
    // Additional from expansion map (Transition/Core Cities - dark blue)
    {name:"County Durham",coverage:"Whole Place",type:"transition_core",lat:54.70,lng:-1.60},
    {name:"Leeds",coverage:"Whole Place",type:"transition_core",lat:53.80,lng:-1.55},
    {name:"Sheffield",coverage:"Whole Place",type:"transition_core",lat:53.38,lng:-1.47},
    {name:"Manchester",coverage:"Whole Place",type:"transition_core",lat:53.48,lng:-2.24},
    {name:"Birmingham",coverage:"Whole Place",type:"transition_core",lat:52.483,lng:-1.889},
    {name:"Bristol",coverage:"Whole Place",type:"transition_core",lat:51.454,lng:-2.597},
    {name:"Plymouth",coverage:"Whole Place",type:"transition_core",lat:50.38,lng:-4.14},
    {name:"Exeter",coverage:"Whole Place",type:"transition_core",lat:50.712,lng:-3.530},
    {name:"Newcastle upon Tyne",coverage:"Whole Place",type:"transition_core",lat:54.98,lng:-1.61},
    // Additional from expansion map (Existing LDP - light blue)
    {name:"Bradford",coverage:"Whole Place",type:"existing_ldp",lat:53.794,lng:-1.752},
    {name:"Hackney",coverage:"MSOAs",type:"existing_ldp",lat:51.55,lng:-0.06},
    {name:"Basildon",coverage:"MSOAs",type:"existing_ldp",lat:51.57,lng:0.46},
    {name:"Tendring",coverage:"MSOAs",type:"existing_ldp",lat:51.868,lng:1.085},
    {name:"Colchester",coverage:"MSOAs",type:"existing_ldp",lat:51.89,lng:0.90},
    {name:"Blackburn with Darwen",coverage:"MSOAs",type:"existing_ldp",lat:53.75,lng:-2.48},
    {name:"Burnley",coverage:"MSOAs",type:"existing_ldp",lat:53.791,lng:-2.244},
    {name:"Hyndburn",coverage:"MSOAs",type:"existing_ldp",lat:53.754,lng:-2.366},
    {name:"Pendle",coverage:"MSOAs",type:"existing_ldp",lat:53.84,lng:-2.21},
    {name:"Rossendale",coverage:"MSOAs",type:"existing_ldp",lat:53.70,lng:-2.28},
    {name:"Oldham",coverage:"MSOAs",type:"existing_ldp",lat:53.54,lng:-2.12},
    {name:"Rochdale",coverage:"MSOAs",type:"existing_ldp",lat:53.61,lng:-2.16},
    // Additional from expansion map (Place Expansion - green)
    {name:"Redcar and Cleveland",coverage:"MSOAs",type:"place_expansion",lat:54.616,lng:-1.059},
    {name:"Middlesbrough",coverage:"MSOAs",type:"place_expansion",lat:54.576,lng:-1.234},
    {name:"East Riding of Yorkshire",coverage:"MSOAs",type:"place_expansion",lat:53.84,lng:-0.70},
    {name:"Wakefield",coverage:"MSOAs",type:"place_expansion",lat:53.68,lng:-1.50},
    {name:"Doncaster",coverage:"MSOAs",type:"place_expansion",lat:53.523,lng:-1.134},
    {name:"Calderdale",coverage:"MSOAs",type:"place_expansion",lat:53.72,lng:-1.86},
    {name:"Bury",coverage:"MSOAs",type:"place_expansion",lat:53.59,lng:-2.30},
    {name:"Tameside",coverage:"MSOAs",type:"place_expansion",lat:53.49,lng:-2.10},
    {name:"Salford",coverage:"MSOAs",type:"place_expansion",lat:53.48,lng:-2.29},
    {name:"Trafford",coverage:"MSOAs",type:"place_expansion",lat:53.42,lng:-2.35},
    {name:"Stockport",coverage:"MSOAs",type:"place_expansion",lat:53.41,lng:-2.16},
    {name:"Wigan",coverage:"MSOAs",type:"place_expansion",lat:53.54,lng:-2.63},
    {name:"Ribble Valley",coverage:"MSOAs",type:"place_expansion",lat:53.87,lng:-2.42},
    {name:"Coventry",coverage:"MSOAs",type:"place_expansion",lat:52.407,lng:-1.510},
    {name:"Solihull",coverage:"MSOAs",type:"place_expansion",lat:52.41,lng:-1.78},
    {name:"Gloucester",coverage:"MSOAs",type:"place_expansion",lat:51.86,lng:-2.24},
    {name:"Luton",coverage:"MSOAs",type:"place_expansion",lat:51.878,lng:-0.415},
    {name:"Ealing",coverage:"MSOAs",type:"place_expansion",lat:51.51,lng:-0.31}
];

// Nature Towns and Cities locations
// Categories: accredited_city, accredited_town, grant_recipient
const NTC_PLACES = [
    // Accredited Nature Cities
    {name:"Plymouth",type:"accredited_city",lat:50.38,lng:-4.14,project:"Plan for Nature and People",website:"https://www.plymouth.gov.uk/plymouth-plan-nature-and-people"},
    {name:"Birmingham",type:"accredited_city",lat:52.483,lng:-1.889,project:"City of Nature Plan",website:"https://naturallybirmingham.org/"},
    // Accredited Nature Towns
    {name:"Bournemouth",type:"accredited_town",lat:50.72,lng:-1.88,project:"BCP Nature Towns",website:"https://bcpprojects.net/nature-towns/"},
    // Grant Recipients (19 partnerships, ~40 towns/cities)
    {name:"Bradford",type:"grant",lat:53.794,lng:-1.752,project:"Green Blue Steppingstones",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"Blackpool",type:"grant",lat:53.818,lng:-3.051,project:"GreenWave: Transforming Urban Nature",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"Liverpool",type:"grant",lat:53.408,lng:-2.992,project:"Liverpool City Region Green Vision",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"Redcar and Cleveland",type:"grant",lat:54.616,lng:-1.059,project:"Tees Urban Nature Network",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"Manchester",type:"grant",lat:53.48,lng:-2.24,project:"Manchester & Salford Green Vision",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"Salford",type:"grant",lat:53.48,lng:-2.29,project:"Manchester & Salford Green Vision",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"Sunderland",type:"grant",lat:54.91,lng:-1.38,project:"Sunderland Urban Green Spaces",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"Bristol",type:"grant",lat:51.454,lng:-2.597,project:"Nature Together",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"Ealing",type:"grant",lat:51.51,lng:-0.31,project:"Regional Park Vision",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"Portsmouth",type:"grant",lat:50.800,lng:-1.091,project:"Green Vision: Urban Nature Revival",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"Lewisham",type:"grant",lat:51.44,lng:-0.01,project:"Lewisham Green Vision",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"Luton",type:"grant",lat:51.878,lng:-0.415,project:"Nature Connection Initiative",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"Norwich",type:"grant",lat:52.63,lng:1.30,project:"NatureCityNorwich",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"Walsall",type:"grant",lat:52.585,lng:-1.982,project:"Green Vision: Nature & Health",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"Coventry",type:"grant",lat:52.407,lng:-1.510,project:"Green Renaissance",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"Torfaen",type:"grant",lat:51.710,lng:-3.045,project:"Torfaen Nature Masterplan",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"Neath Port Talbot",type:"grant",lat:51.595,lng:-3.782,project:"Nature's Back in Town",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"Fife",type:"grant",lat:56.07,lng:-3.46,project:"Transforming Fife's Greenspace",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"North Lanarkshire",type:"grant",lat:55.86,lng:-3.96,project:"NL Nearer to Nature",website:"https://naturetownsandcities.org.uk/grants/"},
    {name:"Belfast",type:"grant",lat:54.60,lng:-5.93,project:"Belfast Nature Recovery Blueprint",website:"https://naturetownsandcities.org.uk/grants/"}
];

// Culture Priority Places (DCMS / Arts Council England, published 22 May 2026)
// Source: https://www.gov.uk/government/publications/dcms-place-targeting/culture-priority-places
// Categories: new (Table 3a - additional 2026 places), existing_dcms (Table 3b - existing
// ACE Priority Places also identified by DCMS), existing_ace (Table 3c - existing ACE PP only)
const ACE_PLACES = [
    // Table 3a: New additional Culture Priority Places (23)
    {name:"Bassetlaw",type:"new",lat:53.30,lng:-1.12},
    {name:"Burnley",type:"new",lat:53.791,lng:-2.244},
    {name:"Cannock Chase",type:"new",lat:52.69,lng:-2.03},
    {name:"Doncaster",type:"new",lat:53.523,lng:-1.134},
    {name:"Erewash",type:"new",lat:52.93,lng:-1.32},
    {name:"Havant",type:"new",lat:50.85,lng:-0.98},
    {name:"Hyndburn",type:"new",lat:53.754,lng:-2.366},
    {name:"King's Lynn and West Norfolk",type:"new",lat:52.75,lng:0.39},
    {name:"North Lincolnshire",type:"new",lat:53.59,lng:-0.65},
    {name:"Pendle",type:"new",lat:53.84,lng:-2.21},
    {name:"Preston",type:"new",lat:53.763,lng:-2.703},
    {name:"Redditch",type:"new",lat:52.31,lng:-1.94},
    {name:"Rossendale",type:"new",lat:53.70,lng:-2.28},
    {name:"Salford",type:"new",lat:53.48,lng:-2.29},
    {name:"St. Helens",type:"new",lat:53.454,lng:-2.737},
    {name:"Sheffield",type:"new",lat:53.38,lng:-1.47},
    {name:"Sunderland",type:"new",lat:54.91,lng:-1.38},
    {name:"Tameside",type:"new",lat:53.49,lng:-2.10},
    {name:"Telford and Wrekin",type:"new",lat:52.68,lng:-2.45},
    {name:"Torbay",type:"new",lat:50.44,lng:-3.53},
    {name:"Wakefield",type:"new",lat:53.68,lng:-1.50},
    {name:"West Lindsey",type:"new",lat:53.39,lng:-0.70},
    {name:"Wyre",type:"new",lat:53.87,lng:-2.92},
    // Table 3b: Existing ACE Priority Places also identified by DCMS methodology (28)
    {name:"Ashfield",type:"existing_dcms",lat:53.090,lng:-1.252},
    {name:"Blackburn with Darwen",type:"existing_dcms",lat:53.75,lng:-2.48},
    {name:"Blackpool",type:"existing_dcms",lat:53.818,lng:-3.051},
    {name:"Bolsover",type:"existing_dcms",lat:53.23,lng:-1.29},
    {name:"Boston",type:"existing_dcms",lat:52.978,lng:-0.024},
    {name:"Chesterfield",type:"existing_dcms",lat:53.235,lng:-1.421},
    {name:"County Durham",type:"existing_dcms",lat:54.70,lng:-1.60},
    {name:"Cumberland",type:"existing_dcms",lat:54.66,lng:-2.90,note:"Only Copeland was a previous ACE Priority Place"},
    {name:"Darlington",type:"existing_dcms",lat:54.52,lng:-1.55,note:"Part of ACE Priority Place 'Tees Valley'"},
    {name:"East Lindsey",type:"existing_dcms",lat:53.259,lng:0.177},
    {name:"Fenland",type:"existing_dcms",lat:52.60,lng:0.10},
    {name:"Great Yarmouth",type:"existing_dcms",lat:52.607,lng:1.731},
    {name:"Hartlepool",type:"existing_dcms",lat:54.686,lng:-1.209,note:"Part of ACE Priority Place 'Tees Valley'"},
    {name:"Isle of Wight",type:"existing_dcms",lat:50.67,lng:-1.32},
    {name:"Knowsley",type:"existing_dcms",lat:53.482,lng:-2.889},
    {name:"North East Lincolnshire",type:"existing_dcms",lat:53.52,lng:-0.10},
    {name:"Nuneaton and Bedworth",type:"existing_dcms",lat:52.52,lng:-1.47},
    {name:"Peterborough",type:"existing_dcms",lat:52.57,lng:-0.24},
    {name:"Redcar and Cleveland",type:"existing_dcms",lat:54.616,lng:-1.059,note:"Part of ACE Priority Place 'Tees Valley'"},
    {name:"Rochdale",type:"existing_dcms",lat:53.61,lng:-2.16},
    {name:"Rotherham",type:"existing_dcms",lat:53.431,lng:-1.356},
    {name:"Sandwell",type:"existing_dcms",lat:52.506,lng:-2.011},
    {name:"Stoke-on-Trent",type:"existing_dcms",lat:53.006,lng:-2.178},
    {name:"Swindon",type:"existing_dcms",lat:51.562,lng:-1.785},
    {name:"Tendring",type:"existing_dcms",lat:51.868,lng:1.085},
    {name:"Walsall",type:"existing_dcms",lat:52.585,lng:-1.982},
    {name:"Wigan",type:"existing_dcms",lat:53.54,lng:-2.63},
    {name:"Wolverhampton",type:"existing_dcms",lat:52.587,lng:-2.128},
    // Table 3c: Existing ACE Priority Places not identified by DCMS methodology (30)
    {name:"Barking and Dagenham",type:"existing_ace",lat:51.540,lng:0.079},
    {name:"Barnsley",type:"existing_ace",lat:53.553,lng:-1.483},
    {name:"Basildon",type:"existing_ace",lat:51.57,lng:0.46},
    {name:"Brent",type:"existing_ace",lat:51.56,lng:-0.27},
    {name:"Crawley",type:"existing_ace",lat:51.11,lng:-0.19},
    {name:"Croydon",type:"existing_ace",lat:51.37,lng:-0.10},
    {name:"Dover",type:"existing_ace",lat:51.13,lng:1.31},
    {name:"Dudley",type:"existing_ace",lat:52.511,lng:-2.082},
    {name:"Enfield",type:"existing_ace",lat:51.65,lng:-0.08},
    {name:"Gloucester",type:"existing_ace",lat:51.86,lng:-2.24},
    {name:"Gosport",type:"existing_ace",lat:50.79,lng:-1.13},
    {name:"Isles of Scilly",type:"existing_ace",lat:49.92,lng:-6.30},
    {name:"Kirklees",type:"existing_ace",lat:53.62,lng:-1.78},
    {name:"Luton",type:"existing_ace",lat:51.878,lng:-0.415},
    {name:"Mansfield",type:"existing_ace",lat:53.14,lng:-1.20},
    {name:"Medway",type:"existing_ace",lat:51.39,lng:0.54},
    {name:"Middlesbrough",type:"existing_ace",lat:54.576,lng:-1.234,note:"Part of ACE Priority Place 'Tees Valley'"},
    {name:"New Forest",type:"existing_ace",lat:50.87,lng:-1.60},
    {name:"Newham",type:"existing_ace",lat:51.53,lng:0.03},
    {name:"North Devon",type:"existing_ace",lat:51.08,lng:-4.06},
    {name:"North East Derbyshire",type:"existing_ace",lat:53.20,lng:-1.40},
    {name:"North Somerset",type:"existing_ace",lat:51.35,lng:-2.94},
    {name:"North Yorkshire",type:"existing_ace",lat:54.25,lng:-1.50},
    {name:"Portsmouth",type:"existing_ace",lat:50.800,lng:-1.091},
    {name:"Rushmoor",type:"existing_ace",lat:51.29,lng:-0.75},
    {name:"Slough",type:"existing_ace",lat:51.51,lng:-0.59},
    {name:"Somerset",type:"existing_ace",lat:51.05,lng:-3.05},
    {name:"South Tyneside",type:"existing_ace",lat:54.958,lng:-1.410},
    {name:"Stockton-on-Tees",type:"existing_ace",lat:54.57,lng:-1.32,note:"Part of ACE Priority Place 'Tees Valley'"},
    {name:"Westmorland and Furness",type:"existing_ace",lat:54.35,lng:-2.85}
];

window.SE_PLACES = SE_PLACES;
window.NTC_PLACES = NTC_PLACES;
window.ACE_PLACES = ACE_PLACES;
